SELECT * FROM customer_database.mytable;
use customer_database;
-- what is total revnue generated by male vs female customer?

select gender,sum(purchase_amount)as revenue
from mytable
group by gender;

-- Which customer use discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from mytable
where discount_applied='Yes' 
and purchase_amount>=(select avg(purchase_amount) 
from mytable);

-- Q3 Which is top 5 product which is highest average review rating??
 select  item_purchased,Round(avg(cast(review_rating as decimal(10,2)))) as "Average Product Rating"
 from mytable
 group by item_purchased
 order by avg(review_rating)desc
 limit 5;

-- Q4 Compare the Average Purchase Amount between Standard and Express shipping.
select shipping_type, Round(avg(purchase_amount),2) 
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5 Do subscribed customer spend more? Compare average spend and total revenue between subscribers and non-sbscribers

select subscription_status,
count(customer_id)as total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from mytable
group by Subscription_status
order by total_revenue desc;

-- Q6 Which 5 product have the highest percentage of purchases wwith discount applied?

select item_purchased,round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2)
as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 Segment customer into new ,returning and loyal based on their total number of previous purchases and show the count of each segment.

with customer_type as(
select customer_id,previous_purchases,
case
 when previous_purchases=1 then 'New'
 when previous_purchases between 2 and 10 then 'returning'
 else 'loyal'
 end as customer_segement
 from mytable
)
select customer_segement,count(*)as 'number of customers'
from customer_type
group by customer_segement;

-- Q8 What is the  3 top most purchased product within each category?

with item_count as(
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)desc) as item_rank
from mytable
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_count
where item_rank<=3;

-- Q9 Are customer are repeat buyers(more than 5 previous purchase)as likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from mytable
where previous_purchases>=5
group by subscription_status;

-- Q10 What is the total revenue contritbute of each age group?
select age_group,
sum(purchase_amount)as total_revenue
from mytable
group by age_group
order by total_revenue desc;